import "@styles/globals.css";
import type { Metadata } from "next";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import { cookies } from "next/headers";
import UserProviderWrapper from "./dashboard/provider/userProvider";
import { useAxiosSSRInterceptor } from "./dashboard/utils/serverSideFetcher";
import InterceptorHoc from "./hocs/interceptorHoc";
import AppLayout from "./layer";

import { Inter } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Alex Petrov",
  description: "Generated by create next app",
};

async function useUseAccessToken() {
  const accessToken = cookies().get("access_token")?.value;

  return { accessToken: accessToken ?? "" };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useAxiosSSRInterceptor();
  const { accessToken } = await useUseAccessToken();

  return (
    <html lang="en">
      <body className={inter.className} style={{ margin: 0 }}>
        <AntdRegistry>
          <UserProviderWrapper accessToken={accessToken}>
            <InterceptorHoc>
              <AppLayout>{children}</AppLayout>
            </InterceptorHoc>
          </UserProviderWrapper>
        </AntdRegistry>
      </body>
    </html>
  );
}
