import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { cookies } from 'next/headers'
import { subscribeSSRInterceptor } from 'utils/serverSideFetcher'
import InterceptorHoc from './hocs/interceptorHoc'
import AppLayout from './layer'

import UserProviderWrapper from './providers/userProvider'
import '@styles/globals.css'

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Alex Petrov',
  description: 'Generated by create next app',
}

async function getAccessTokenFromCookies() {
  const accessToken = (await cookies()).get('access_token')?.value

  return { accessToken: accessToken ?? '' }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  subscribeSSRInterceptor()
  const { accessToken } = await getAccessTokenFromCookies()

  return (
    <html lang="en">
      <body className={inter.className} style={{ margin: 0 }}>
        <UserProviderWrapper accessToken={accessToken}>
          <InterceptorHoc>
            <AppLayout>{children}</AppLayout>
          </InterceptorHoc>
        </UserProviderWrapper>
      </body>
    </html>
  )
}
